apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster-auth-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git
    targetRevision: HEAD
    path: gitops/applications/auth-service
    
  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster-flag-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git
    targetRevision: HEAD
    path: gitops/applications/flag-service
    
  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster-targeting-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git
    targetRevision: HEAD
    path: gitops/applications/targeting-service
    
  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster-evaluation-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git
    targetRevision: HEAD
    path: gitops/applications/evaluation-service
    
  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster-analytics-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git
    targetRevision: HEAD
    path: gitops/applications/analytics-service
    
  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
