apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/instance: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: togglemaster
  labels:
    name: togglemaster
---
apiVersion: v1
kind: Namespace
metadata:
  name: togglemaster-secrets
  labels:
    name: togglemaster-secrets
