apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-creds-github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git
  password: YOUR_GITHUB_TOKEN
  username: not_used
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  admin.password: argocd  # IMPORTANTE: Mude isso em produção!
  server.secretkey: "1234567890abcdef1234567890abcdef1234567890abcdef"
